### ISSUE TITLE
Feature request: Pagnation and Search for contacts

### ISSUE THREAD

**Issue by riotweb** [owncloudarchive/contacts#1138] opened 2016-02-06 10:22 UTC
Hi !
I think it will be helpful to have a search form for contacts and pagnation coz long loading time with big addressbook. :)

**Comment by RealRancor** [comment] 2016-02-06 13:43
@riotweb Search is already planned to be brought back: https://github.com/owncloud/contacts/pull/966 where you can find a lot of duplicates linked in its title.

Pagnation is a duplicate of https://github.com/owncloud/contacts/issues/1133, https://github.com/owncloud/contacts/issues/582, https://github.com/owncloud/contacts/issues/1039

So i think that one can be closed to avoid having multiple issues about the same issue open.

**Closed** 2016-03-03 18:24 UTC
