### ISSUE TITLE
Synchronizing contacts to Thunderbird addressbook has been broken for more than six months

### ISSUE THREAD

**Issue by eriklogtenberg** [owncloudarchive/contacts#608] opened 2014-08-19 11:51 UTC
To synchronize Owncloud contacts to Thunderbird addressbook, the use of a carddav plugin for Thunderbird is required. There is one such plugin, the SoGo Connector found here:
http://www.sogo.nu/downloads/frontends.html

This SoGo Connector has a bug, that causes only the last email address for each contact to be synced. Usually the preferred email address is the first, and that email address will not be synced. This bug was reported in january this year:
http://www.sogo.nu/bugs/view.php?id=2570
Unfortunately since then, this bug has been confirmed by multiple users, with different environments, but nobody has stepped up to fix the bug yet, even though it is a particularly nasty bug.

Now since this bug renders the whole combination Owncloud/Thunderbird more or less useless, which seems to be kind of a big deal, I am also reporting it against Owncloud. Also, even though I expect the bug to be in the SoGo Connector, at this moment that is not even certain. It might be a bug in Thunderbird Addressbook or it might just as well be a bug in Owncloud carddav server. As far as I can tell, this hasn't been triaged yet.

Please someone take a look at this issue, and help fixing it, regardless of where the bug exactly lives.

**Comment by fekepp** [comment] 2015-06-23 15:16
I created a few test contacts in Thunderbird with Inverse SOGo Connector, via Akonadi DAV Groupware Agent (used by Kontact, KAddressBook, etc.), and directly in ownCloud.

Version of ownCloud is 8.0.4 (stable).

Important to note:
Thunderbird address book does not provide more than two fields for entries, i.e., Email and Additional Email.

Comments and exports (from Akonadi) shown below.

Test1 Testname (created via Akonadi):
* I added two email addresses of which the first is automatically marked as preferred
* "TYPE=PREF" automatically set for the first address
* Result: both email addresses show up in Kontact and ownCloud, but only the first in the Thunderbird address book

    BEGIN:VCARD
    VERSION:4.0
    EMAIL;TYPE=PREF:test1.1@testname.com
    EMAIL:test1.2@testname.com
    FN:Test1 Testname
    N:Testname;Test1;;;
    UID:b1a1846f-dd41-475a-83d1-ac8dc137c5dd
    END:VCARD


Test2 Testname (created via Inverse SOGo Connector):
* I used both the email and additional email fields of the entry
* "TYPE=work,PREF" automatically set for the first ("email") address
* "TYPE=home" automatically set for the second ("additional email") address
* Result: both email addresses show up in all systems, also in Thunderbird address book

    BEGIN:VCARD
    VERSION:4.0
    EMAIL;TYPE=work,PREF:test2.1@testname.com
    EMAIL;TYPE=home:test2.2@testname.com
    FN:Test2 Testname
    N:Testname;Test2;;;
    PRODID:-//ownCloud//NONSGML Contacts 0.3.0.18//EN
    UID:C6A87B7B-B810-0001-96F4-1B80A4563C00
    X-MOZILLA-HTML:FALSE
    END:VCARD


Test3 Testname (created via ownCloud):
* I used only default entries for email, i.e., all entries are of type work and no preference
* "TYPE=WORK" for both addresses (PREF seems to be set by Akonadi where I did the export)
* Result: both email addresses show up in Kontact and ownCloud, but only the first in the Thunderbird address book

    BEGIN:VCARD
    VERSION:4.0
    EMAIL;TYPE=WORK,PREF:test3.1@testname.com
    EMAIL;TYPE=WORK:test3.2@testname.com
    FN:Test3 Testname
    N:Testname;Test3;;;
    PRODID:-//ownCloud//NONSGML Contacts 0.3.0.18//EN
    UID:77fe6c46-606a-451e-9ba5-931405bb9343@cloud.xyz
    END:VCARD


Test4 Testname (created via ownCloud):
* I marked the first address as work and preferred and the second email as home and not preferred
* "TYPE=PREF,WORK" for first address
* "TYPE=HOME" for second addresse
* Result: both email addresses show up in all systems, also in Thunderbird address book

    BEGIN:VCARD
    VERSION:4.0
    EMAIL;TYPE=PREF,WORK:test4.1@testname.com
    EMAIL;TYPE=HOME:test4.2@testname.com
    FN:Test4 Testname
    N:Testname;Test4;;;
    PRODID:-//ownCloud//NONSGML Contacts 0.3.0.18//EN
    UID:1e270d45-a0a6-46eb-bf02-2c9ad598db82@cloud.xyz
    END:VCARD


I tested a bit more and don't want to paste all this here. As you see it is all about the "type" part of the email entry. After some try and error it seems that the "Additional Email" entry is mapped by the Inverse SOGo Connector to the "last" email address with "TYPE=home". From all other email addresses the "last" email address which is not "TYPE=home" is taken for the "Email" entry.

Summary:
Email addresses seem to be synced by the Inverse SOGo Connector in the following way:
* "Email"
    * last email address entry which has not "TYPE=home"
* "Additional Email"
   * last email address entry which has "TYPE=home"

Important to note:
If not all email addresses show up (or you have more than two in the contact) and edit the contact in the Thunderbird address book, only the email address(es) shown in the Thunderbird address book will be synced back by the Inverse SOGo Connector and all others are deleted.

Workaround:
For two Email addresses (which is often the case, i.e., private and business email) you may mark one as "home" and one as "work" address. Both will be synced bidirectional and appear as email (work) and additional email (home) in the Thunderbird address book. But, some clients may not support this. The ownCloud contacts app works.


However, even if the only-work-and-home support may be a feature, I would consider the deletion of additional payload (e.g., non-visible email addresses) by the SOGo Connector as a bug of the connector as it causes data loss.

**Comment by RealRancor** [comment] 2016-10-15 16:11
SOGo has now fixed this known bug in their product:

https://sogo.nu/bugs/bug_relationship_graph.php?bug_id=2570&graph=relation

with the upcoming 31.0.4. of SOGo connector:

https://github.com/inverse-inc/sogo-connector.tb31/commit/2253f36fb2093db6749127ddd48270f70675ed72

That version of SOGo is not released yet but the issue here could be closed anyway as it is not a bug in the oC contacts App (and the App here is deprecated anyway).

**Closed** 2016-10-17 04:55 UTC
